### ISSUE TITLE
"ВКЛЮЧИТЕ -Трансляция аудиозаписей- К СЕБЕ НА СТРАНИЦУ!!!"

### ISSUE THREAD

**Issue by Prvxce** [menleev/vk-rpc-to-discord#1]
It was working fine a day ago, until today when all of a sudden I got this message "ВКЛЮЧИТЕ -Трансляция аудиозаписей- К СЕБЕ НА СТРАНИЦУ!!!"

I translated it and I checked my VK to see that it is broadcasting my audio, so I reset my id didnt work, reinstalled didnt work, turning off broadcasitng and on again didnt work...
![image](https://user-images.githubusercontent.com/53024313/235126859-ef25a636-0b01-4970-ab4c-51e7528c3327.png)

I was wondering if you had a fix for this?

**Comment by menleev** [comment]
![image](https://user-images.githubusercontent.com/110269230/236682031-45964899-b64a-43fd-9e86-750d82124a83.png)
Everything works:\

**Comment by menleev** [comment]
![image](https://user-images.githubusercontent.com/110269230/236682087-2ecbbb2d-c90f-447e-aae1-d2de395eb46a.png)
Make your page visible to everyone
